"""
Digest Agent
============
Generates a weekly sprint summary from GitLab activity and delivers it to
Slack. Ported from github.com/Sakethv7/ai-digest with Gemini swapped for
Claude via the Anthropic SDK.

Trigger: weekly cron (every Monday at 09:00 local time)
"""
from __future__ import annotations

import os
from datetime import datetime, timedelta, timezone
from typing import Any

from agents.base_agent import BaseAgent
from agents.digest_agent.prompts import DIGEST_PROMPT, SYSTEM_PROMPT
from tools import anthropic_client, gitlab_client, slack_notifier


def _fmt_mrs(mrs: list[dict]) -> str:
    if not mrs:
        return "  (none)"
    lines = []
    for mr in mrs[:30]:
        labels = f" [{', '.join(mr['labels'])}]" if mr["labels"] else ""
        lines.append(f"  - !{mr['iid']} {mr['title']} — {mr['author']}{labels}")
    return "\n".join(lines)


def _fmt_issues(issues: list[dict]) -> str:
    if not issues:
        return "  (none)"
    lines = []
    for issue in issues[:30]:
        assignees = ", ".join(issue["assignees"]) if issue["assignees"] else "unassigned"
        lines.append(f"  - #{issue['iid']} {issue['title']} ({assignees})")
    return "\n".join(lines)


def _fmt_commits(commits: list[dict]) -> str:
    if not commits:
        return "  (none)"
    lines = [f"  - [{c['short_id']}] {c['title']} — {c['author_name']}" for c in commits[:20]]
    return "\n".join(lines)


class DigestAgent(BaseAgent):
    name = "digest"

    def run(self, context: dict[str, Any]) -> dict[str, Any]:
        """
        context keys (all optional, fall back to env / defaults):
          - project_id  : GitLab project ID
          - weeks_back  : how many weeks to look back (default 1)
          - post_slack  : bool, default True
        """
        project_id = context.get("project_id") or os.environ.get("GITLAB_PROJECT_ID")
        weeks_back = int(context.get("weeks_back", os.environ.get("SPRINT_WEEKS", 1)))

        now = datetime.now(timezone.utc)
        since = now - timedelta(weeks=weeks_back)
        date_range = f"{since.strftime('%Y-%m-%d')} → {now.strftime('%Y-%m-%d')}"

        # ── Fetch GitLab data ────────────────────────────────────────────────
        project = gitlab_client.get_project(project_id)

        mrs = gitlab_client.get_merged_mrs(project, since)
        issues = gitlab_client.get_closed_issues(project, since)
        commits = gitlab_client.get_commits(project, since)
        pipeline_summary = gitlab_client.get_pipeline_summary(project, since)

        pass_rate = (
            round(pipeline_summary["passed"] / pipeline_summary["total"] * 100)
            if pipeline_summary["total"]
            else 0
        )

        # ── Build prompt ─────────────────────────────────────────────────────
        prompt = DIGEST_PROMPT.format(
            date_range=date_range,
            mr_count=len(mrs),
            mrs=_fmt_mrs(mrs),
            issue_count=len(issues),
            issues=_fmt_issues(issues),
            commit_count=len(commits),
            commits=_fmt_commits(commits),
            pipeline_total=pipeline_summary["total"],
            pipeline_passed=pipeline_summary["passed"],
            pipeline_failed=pipeline_summary["failed"],
            pass_rate=pass_rate,
        )

        # ── Call Claude ──────────────────────────────────────────────────────
        digest_text = anthropic_client.complete(
            prompt=prompt,
            system=SYSTEM_PROMPT,
            model="claude-sonnet-4-6",
            max_tokens=3500,
            temperature=0.6,
        )

        # ── Deliver ──────────────────────────────────────────────────────────
        title = f"🗓️ Weekly Sprint Digest — {date_range}"
        footer = f"_Generated by SDLC Intelligence Agent · Claude claude-sonnet-4-6 · {now.strftime('%Y-%m-%d %H:%M UTC')}_"

        if context.get("post_slack", True):
            slack_notifier.post(title=title, body=digest_text, footer=footer)

        return {
            "status": "ok",
            "output": digest_text,
            "title": title,
            "date_range": date_range,
            "stats": {
                "mrs": len(mrs),
                "issues": len(issues),
                "commits": len(commits),
                "pipeline": pipeline_summary,
            },
        }
